version: 1

service:
  name: test-app
  version: 1.0.0

idpAuthentications:
  - id: auth_client
    type: clientCredentials
    authEndpoint: "{{KEYCLOCK_AUTH_ENDPOINT}}"
    clientId: "{{KEYCLOCK_AUTH_CLIENT_ID}}"
    clientSecret: "{{KEYCLOCK_AUTH_CLIENT_SECRET}}"

api:
  endpoints:
    - route: /api/mock
      method: get
      actionId: get_customer_mock

    - route: /api/customer
      method: get
      actionId: get_customer
      
actions:
  - id: get_customer_mock
    type: httpRequestMock
    http:
      mock:
        body: "{ 'Say':'Hello' }"
        contentType: "application/json"
        statusCode: 201
        headers: 
          "mock1": "value1"
          "mock2": "value2"
          "mock3": "value2"

  - id: get_customer
    type: httpRequest
    http:
      request:
        method: get
        url: 'http://localhost:{{PORT}}/api/mock'
        mapRequestHeaders:
          - "mock1"
          - "mock2:change2"
        mapFixedHeaders:
          "req1": "value1"
          "req2": "value2"
      response:
        mapResponseHeaders:
          - "mock1"
          - "mock2:change2"
        mapFixedHeaders:
          "resp1": "value1"
          "resp2": "value2"


contractMap:
  id: before_customer
  