version: 1

service:
  name: test-app
  version: 1.0.0

api:
  endpoints:
    route: "api/customer"
    method: get
    actionId: get_customer

actions:
  id: get_customer
  type: httpRequestMock
  mock:
    value: "Hi"
    contentType: "application/json"
    method: get