version: 1

service:
  name: test-app
  version: 1.0.0

api:
  endpoints:
    - route: /api/customer
      method: get
      actionId: get_customer
    
actions:
  - id: get_customer
    type: httpRequestMock
    mock:
      body: "{ 'Say':'Hello' }"
      contentType: "application/json"
      statusCode: 201
      headers: 
       "key1": "value1"
       "key2": "value2"
