version: 1

connections:
  redis:
  - id: redis_default2
    addresses: 
    - '{{REDIS_CONNECTION}}'
    #password: 123456
    #db: 0

idemps:
  - id: idemp_2
    redisConnectionId: redis_default2
    key: "{{bodyContext.currentBody}}"
    ttlInSeconds: 300

api:
  endpoints:
    - route: /api/mock2
      method: post
      actionId: mock_mirror2
      idempId: idemp_2

actions:
  - id: mock_mirror2
    type: httpRequestMock
    http:
      mock:
        mirrorBody: true