version: 1

service:
  name: "{{SERVICE_NAME}}"
  version: 1.0.0

tokenCredentials:
  - id: custom_client
    type: custom_authentication
    authEndpoint: https://cat.api.firstdata.com/sba/token/
    forceReload: 10m
    custom:
      method: post
      requestHeaders:
        Content-Type: application/x-www-form-urlencoded
      requestBody:
        grant_type: "password"
        client_id: "bwa"
        username: "int_afinz_apis"
        password: "vK8FIxggtB28UHW4U9VG95d@"
      configs:
        accessTokenPropertyName: "access_token"
        tokenType: ""
        headerName: "auth"

api:
  endpoints:
    - route: /api/hmac_test
      method: post
      flowActionId:
        - var_context
        - func_concate
        - func_hash
        - call_client

actions:
  - id: func_hash
    type: funcHash
    body:
      preserveCurrentBody: true
      useValue: "{{bodyContext.actions.func_concate}}"
    func:
      hash:
        alg: SHA-256  #SHA-1, SHA-512, MD5 ...
        key: 'N93nmFmoY0NzSMC5'

  - id: var_context
    type: funcVarContext
    body:
      preserveCurrentBody: true
    func:
      vars:
        "Timestamp": "{{func.timestamp(milli)}}"
        "ApiKey": "X0GW3QGOYFn4r7DHcVC8KuatUnNs6MGB"
        "ClientRequestId": "BqPwwuCODCPWFwboS605HAM"

  - id: func_concate
    type: funcStringConcate
    body:
      preserveCurrentBody: true
    func:
      concate:
      - "{{bodyContext.actions.var_context.ApiKey}}"
      - "{{bodyContext.actions.var_context.ClientRequestId}}"
      - "{{bodyContext.actions.var_context.Timestamp}}"
      - "{{bodyContext.currentBody}}"


  - id: call_client
    type: httpRequest
    http:
      request:
        headers: 
          "Message-Signature": "{{bodyContext.actions.func_hash}}"
          "Timestamp": "{{bodyContext.actions.var_context.Timestamp}}"
          "Api-Key": "{{bodyContext.actions.var_context.ApiKey}}"
          "Client-Request-Id": "{{bodyContext.actions.var_context.ClientRequestId}}"
        method: post
        tokenCredentialId: custom_client
        url: 'https://cat.api.firstdata.com/bwa/wsm/prepayments/consultations/consultPrepayment'

