version: 1

service:
  name: test-app
  version: 1.0.0

api:
  endpoints:
    - route: /api/mock
      method: get
      actionId: get_customer_mock

    - route: /api/customer
      method: get
      actionId: get_customer
      
actions:
  - id: get_customer_mock
    type: httpRequestMock
    mock:
      body: "{ 'Say':'Hello' }"
      contentType: "application/json"
      statusCode: 201
      headers: 
       "key1": "value1"
       "key2": "value2"

  - id: get_customer
    type: httpRequest
    request:
      method: get
      url: 'http://localhost:8085/api/mock'
      fixedHeaders: 
       "key1": "value1"
       "key2": "value2"


