version: 1

api:
  authorization:
    algorithm: SHA-256
    key: {{HMAC_KEY}}
    type: hmac
    signatureRef: {{bodyContext.signature}}
    #useCurrentBody: true
    concatenateFields:
    - {{bodyContext.id}}
    - {{bodyContext.createdAt}}
    - {{bodyContext.payload}}
