name: Build and Push Docker Image with Git Tag

on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
  
  build-and-publish-docker:
    needs: build
    name: 'build and publish docker'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./Wrench/App
          push: true
          tags: ivanmds2/wrenchgo:latest, ivanmds2/wrenchgo:${{ github.run_number }}
    